---
title: "User Study Analysis"
output:
  html_document:
    toc: true
    toc_float: true
    theme: flatly
    code_folding: show
---

# Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE,
                      fig.width = 8, fig.height = 5)
```


# Packages

```{r packages}
library(jsonlite)
library(tidyverse)
library(ggplot2)
library(knitr)
library(kableExtra)
library(boot)
```

# Data Loading & Structuring

```{r load-data}

user_study_raw <- fromJSON("../user_study_data/user_study_judged.json")

df_u_raw <- as_tibble(user_study_raw) %>%
  select(case_id, condition, topic, pre_opinion, classified_response) %>%
  unnest(classified_response) %>% 
  select(case_id, condition, topic, pre_opinion, turn, role, mean_score)

df_u_raw <- df_u_raw %>%
  mutate(
    user_stance = factor(case_when(
      pre_opinion == 4 ~ "neutral",
      pre_opinion > 4 ~ "pro",
      pre_opinion < 4 ~ "con",
    ), levels = c("con", "neutral", "pro"))
  ) 



# By conditions

df_u_unp <- df_u_raw %>% 
  filter(condition == "unprompted") 

df_u_syc <- df_u_raw %>% 
  filter(condition == "sycophantic") 

df_u_cont <- df_u_raw %>% 
  filter(condition == "contrarian") 


# Assistant turns
# & remove neutral

df_u_unp_assistant <- df_u_unp %>% 
  filter(role == "assistant") %>% 
  filter(user_stance != "neutral") 

df_u_syc_assistant <- df_u_syc %>% 
  filter(role == "assistant") %>% 
  filter(user_stance != "neutral") 

df_u_cont_assistant <- df_u_cont %>% 
  filter(role == "assistant") %>% 
  filter(user_stance != "neutral") 



# User turns
# & remove neutral


df_u_unp_user <- df_u_unp %>% 
  filter(role == "user") %>%
  filter(user_stance != "neutral") 

df_u_syc_user <- df_u_syc %>% 
  filter(role == "user") %>%
  filter(user_stance != "neutral") 

df_u_cont_user <- df_u_cont %>% 
  filter(role == "user") %>%
  filter(user_stance != "neutral") 


```


# Assistant Turns Plots

```{r}

unp_plot <- ggplot(df_u_unp_assistant, aes(x = turn, y = mean_score, color = user_stance, fill = user_stance)) +
  geom_jitter(width = 0.05, height = 0.05, alpha = 0.3, size = 1) +
  stat_summary(geom = "ribbon", fun.data = mean_cl_normal, alpha = 0.2, color = NA) +
  stat_summary(fun = mean, geom = "line", linewidth = 1) +
  stat_summary(fun = mean, geom = "point", size = 2.5, shape = 21, color = "white", stroke = 1) +
  scale_y_continuous(limits = c(-2, 2), breaks = seq(-2, 2, 1)) +
  scale_x_continuous(limits = c(1, 8)) +
  labs(
    title = "Evolution of Model Stance over 8 Turns (Unprompted Condition)",
    # subtitle = "Model responses to synthetic pro/con user inputs across 5 debate topics (T=0; 2 replications).\nPoints show mean stance scores calculated from 3 sentences per response. Ribbon shows 95% Confidence Interval.",
    color = "User Stance", 
    fill = "User Stance",
    x = "Conversation Turn",
    y = "Classification Score (Alignment with Topic)"
  ) +
  theme_minimal() +
  theme(legend.position = "bottom") 


syc_plot <- ggplot(df_u_syc_assistant, aes(x = turn, y = mean_score, color = user_stance, fill = user_stance)) +
  geom_jitter(width = 0.05, height = 0.05, alpha = 0.3, size = 1) +
  stat_summary(geom = "ribbon", fun.data = mean_cl_normal, alpha = 0.2, color = NA) +
  stat_summary(fun = mean, geom = "line", linewidth = 1) +
  stat_summary(fun = mean, geom = "point", size = 2.5, shape = 21, color = "white", stroke = 1) +
  scale_y_continuous(limits = c(-2, 2), breaks = seq(-2, 2, 1)) +
  scale_x_continuous(limits = c(1, 8)) +
  labs(
    title = "Evolution of Model Stance over 8 Turns (Sycophantic Condition)",
    # subtitle = "Model responses to synthetic pro/con user inputs across 5 debate topics (T=0; 2 replications).\nPoints show mean stance scores calculated from 3 sentences per response. Ribbon shows 95% Confidence Interval.",
    color = "User Stance", 
    fill = "User Stance",
    x = "Conversation Turn",
    y = "Classification Score (Alignment with Topic)"
  ) +
  theme_minimal() +
  theme(legend.position = "bottom") 

cont_plot <- ggplot(df_u_cont_assistant, aes(x = turn, y = mean_score, color = user_stance, fill = user_stance)) +
  geom_jitter(width = 0.05, height = 0.05, alpha = 0.3, size = 1) +
  stat_summary(geom = "ribbon", fun.data = mean_cl_normal, alpha = 0.2, color = NA) +
  stat_summary(fun = mean, geom = "line", linewidth = 1) +
  stat_summary(fun = mean, geom = "point", size = 2.5, shape = 21, color = "white", stroke = 1) +
  scale_y_continuous(limits = c(-2, 2), breaks = seq(-2, 2, 1)) +
  scale_x_continuous(limits = c(1, 8)) +
  labs(
    title = "Evolution of Model Stance over 8 Turns (Contrarian Condition)",
    # subtitle = "Model responses to synthetic pro/con user inputs across 5 debate topics (T=0; 2 replications).\nPoints show mean stance scores calculated from 3 sentences per response. Ribbon shows 95% Confidence Interval.",
    color = "User Stance", 
    fill = "User Stance",
    x = "Conversation Turn",
    y = "Classification Score (Alignment with Topic)"
  ) +
  theme_minimal() +
  theme(legend.position = "bottom") 

unp_plot
syc_plot
cont_plot
# ggsave("user_study_unprompted_plot.pdf", plot = unp_plot, width=8, height=5)
# ggsave("user_study_sycophantic_plot.pdf", plot = syc_plot, width=8, height=5)
# ggsave("user_study_contrarian_plot.pdf", plot = cont_plot, width=8, height=5)

```




# User Turns Plots

```{r}

unp_plot_user <- ggplot(df_u_unp_user, aes(x = turn, y = mean_score, color = user_stance, fill = user_stance)) +
  geom_jitter(width = 0.05, height = 0.05, alpha = 0.3, size = 1) +
  stat_summary(geom = "ribbon", fun.data = mean_cl_normal, alpha = 0.2, color = NA) +
  stat_summary(fun = mean, geom = "line", linewidth = 1) +
  stat_summary(fun = mean, geom = "point", size = 2.5, shape = 21, color = "white", stroke = 1) +
  scale_y_continuous(limits = c(-2, 2), breaks = seq(-2, 2, 1)) +
  scale_x_continuous(limits = c(1, 8)) +
  labs(
    title = "Evolution of User Stance over 8 Turns (Unprompted Condition)",
    # subtitle = "Model responses to synthetic pro/con user inputs across 5 debate topics (T=0; 2 replications).\nPoints show mean stance scores calculated from 3 sentences per response. Ribbon shows 95% Confidence Interval.",
    color = "User Stance", 
    fill = "User Stance",
    x = "Conversation Turn",
    y = "Classification Score (Alignment with Topic)"
  ) +
  theme_minimal() +
  theme(legend.position = "bottom") 


syc_plot_user <- ggplot(df_u_syc_user, aes(x = turn, y = mean_score, color = user_stance, fill = user_stance)) +
  geom_jitter(width = 0.05, height = 0.05, alpha = 0.3, size = 1) +
  stat_summary(geom = "ribbon", fun.data = mean_cl_normal, alpha = 0.2, color = NA) +
  stat_summary(fun = mean, geom = "line", linewidth = 1) +
  stat_summary(fun = mean, geom = "point", size = 2.5, shape = 21, color = "white", stroke = 1) +
  scale_y_continuous(limits = c(-2, 2), breaks = seq(-2, 2, 1)) +
  scale_x_continuous(limits = c(1, 8)) +
  labs(
    title = "Evolution of User Stance over 8 Turns (Sycophantic Condition)",
    # subtitle = "Model responses to synthetic pro/con user inputs across 5 debate topics (T=0; 2 replications).\nPoints show mean stance scores calculated from 3 sentences per response. Ribbon shows 95% Confidence Interval.",
    color = "User Stance", 
    fill = "User Stance",
    x = "Conversation Turn",
    y = "Classification Score (Alignment with Topic)"
  ) +
  theme_minimal() +
  theme(legend.position = "bottom") 

cont_plot_user <- ggplot(df_u_cont_user, aes(x = turn, y = mean_score, color = user_stance, fill = user_stance)) +
  geom_jitter(width = 0.05, height = 0.05, alpha = 0.3, size = 1) +
  stat_summary(geom = "ribbon", fun.data = mean_cl_normal, alpha = 0.2, color = NA) +
  stat_summary(fun = mean, geom = "line", linewidth = 1) +
  stat_summary(fun = mean, geom = "point", size = 2.5, shape = 21, color = "white", stroke = 1) +
  scale_y_continuous(limits = c(-2, 2), breaks = seq(-2, 2, 1)) +
  scale_x_continuous(limits = c(1, 8)) +
  labs(
    title = "Evolution of User Stance over 8 Turns (Contrarian Condition)",
    # subtitle = "Model responses to synthetic pro/con user inputs across 5 debate topics (T=0; 2 replications).\nPoints show mean stance scores calculated from 3 sentences per response. Ribbon shows 95% Confidence Interval.",
    color = "User Stance", 
    fill = "User Stance",
    x = "Conversation Turn",
    y = "Classification Score (Alignment with Topic)"
  ) +
  theme_minimal() +
  theme(legend.position = "bottom") 

unp_plot_user
syc_plot_user
cont_plot_user
# ggsave("user_study_unprompted_plot_user.pdf", plot = unp_plot, width=8, height=5)
# ggsave("user_study_sycophantic_plot_user.pdf", plot = syc_plot, width=8, height=5)
# ggsave("user_study_contrarian_plot_user.pdf", plot = cont_plot, width=8, height=5)

```








